[package]
authors = ["Christopher J. McClellan <chris.mcclellan203@gmail.com>"]
edition = "2018"
readme = "README.md"
name = "stm32f3-discovery"
description = "Board support package for the STM32F3DISCOVERY board"
repository = "https://rubberduck203/stm32f3-discovery"
license = "MIT OR Apache-2.0"
maintenance = { status = "experimental" }
version = "0.1.0"
exclude = [
    ".vscode/*",
]

[dependencies]
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"

# For the stm32f303vc mcu
[dependencies.stm32f3xx-hal]
features = ["stm32f303xc", "rt"]
version = "0.4.0"

[dev-dependencies]
cortex-m-semihosting = "0.3.3"
panic-halt = "0.2.0"
panic-itm = "0.4.1"

# # this lets you use `cargo fix`!
# [[bin]]
# name = "stm32f3-discovery"
# test = false
# bench = false

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations