name: Rust

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install ARM toolchain
      run: rustup target add thumbv7em-none-eabihf
    - name: Build
      run: cargo build --verbose
    #- name: Run tests
    #  run: cargo test --verbose
